DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('protein_profiler/', include('protein_profiler.urls'))
]

protein_profiler/urls.py
from django.urls import path
from . import views


app_name = "protein_profiler"

urlpatterns = [
    path('test_view/', views.test_view, name = "test_view"),
    path('prot_char/', views.prot_char, name = "prot_char"),
    path('submitted_prot_char/', views.submitted_prot_char, name = "submitted_prot_char"),
    path('download_csv/', views.download_csv, name = "download_csv"),
    path('view_protein/<str:id>/', views.view_protein, name='view_protein'),
    path('plot/<str:choice>/', views.plot, name='plot'),
    path('how_to_use/', views.how_to_use, name = 'how_to_use'),
    path('download/', views.download, name = 'download'),
    path('download_zip_file/', views.download_zip_file, name = 'download_zip_file'),
    path('publication/', views.publication, name = 'publication'),
    path('download_plots/', views.download_plots, name = 'download_plots'),
    path('contact/', views.contact, name = 'contact')
]

protein_profiler/models.py
from django.db import models

# Create your models here.

protein_profiler/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField

class proteinForm(forms.Form):
    protein_text = forms.CharField(widget=forms.Textarea(attrs={"rows":8, 
                                                                "cols":40,
                                                                "placeholder":">sp|A0A7H0DMZ8|IL18B_MONPV Interleukin-18-binding protein\n MRILFLIAFMYGCVHSYVNAVETKCPNLAIVTSSGEFHCSGCVERMPGFSYMYWLANDMKSDEDTKFIEHLGGGIKEDETVRTTDGGITTLRKVLHVTDTNKFAHYRFTCVLITLDGVSKKNIWLK"}), required=False)
    uploaded_file = forms.FileField(
        label = 'Upload your proteins in .FASTA format', required=False)
    


class ContactForm(forms.Form):
    subject = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea(attrs={"rows":10, 
                                                                "cols":40,
                                                                "placeholder":"Type your message here"}),
                                                                required=True)
    captcha = ReCaptchaField()

protein_profiler/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .forms import proteinForm, ContactForm

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqUtils.ProtParam import ProteinAnalysis
from Bio.SeqUtils import IsoelectricPoint
from io import StringIO
from io import BytesIO
import re
import csv
import matplotlib
from collections import Counter

matplotlib.use('agg')  # Use the Agg backend

import matplotlib.pyplot as plt
from io import BytesIO
import base64

from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json
import requests
import zipfile
from django.conf import settings
import os
import tempfile
import shutil

from django.core.mail import EmailMessage, get_connection
from django.conf import settings

# Calculations
def gravy(protein):
    gravy_values = {
        'A':  1.8 , 
        'R': -4.5,  
        'N': -3.5,  
        'D': -3.5,  
        'C':  2.5,  
        'Q': -3.5,  
        'E': -3.5,  
        'G': -0.4,  
        'H': -3.2,  
        'I':  4.5,  
        'L':  3.8,  
        'K': -3.9,  
        'M':  1.9,  
        'F':  2.8,  
        'P': -1.6,  
        'S': -0.8,  
        'T': -0.7,  
        'W': -0.9,  
        'Y': -1.3,  
        'V':  4.2  
        }

    sequence_gravy = []
    for aminoacid in protein:
        gravy_value = gravy_values.get(aminoacid)
        sequence_gravy.append(gravy_value)
    return round(sum(sequence_gravy)/len(protein),2)

def aliphatic_index(protein):

    a = 2.9
    b = 3.9

    counts = {
        'A': 0, 
        'V': 0,
        'I': 0, 
        'L': 0, 
    }

    total_amino_acids = len(protein)

    for amino_acid in protein:
        if amino_acid in counts:
            counts[amino_acid] += 1

    mole_percent = {aa: (count / total_amino_acids) * 100 for aa, count in counts.items()}

    aliphatic_index = mole_percent['A'] + a * mole_percent['V'] + b * (mole_percent['I'] + mole_percent['L'])

    return round(aliphatic_index,2)

def instability_index(protein):
    x = ProteinAnalysis(protein)
    return(round(x.instability_index(),2))

def molecular_weight(protein):
    x = ProteinAnalysis(protein)
    return(round(x.molecular_weight(),2))

def aromaticity(protein):
    x = ProteinAnalysis(protein)
    return(round(x.aromaticity(),2))

pKa = {
    'Cterm': 3.55,
    'Nterm': 7.5,
    'C': 9.0,
    'D': 4.05,
    'E': 4.45,
    'H': 5.98,
    'K': 10.0,
    'R': 12.0,
    'Y': 10.0
}

def net_charge(seq, pH):
    seq = seq.upper()
    counts = Counter(seq)

    charge = 0.0

    # N-terminus
    charge += 1 / (1 + 10**(pH - pKa['Nterm']))

    # C-terminus
    charge += -1 / (1 + 10**(pKa['Cterm'] - pH))

    # Positive residues
    for aa in ['K', 'R', 'H']:
        charge += counts[aa] / (1 + 10**(pH - pKa[aa]))

    # Negative residues
    for aa in ['D', 'E', 'C', 'Y']:
        charge += -counts[aa] / (1 + 10**(pKa[aa] - pH))

    return charge

def isoelectric_point(seq, tol=1e-4):
    low, high = 0.0, 14.0

    while high - low > tol:
        mid = (low + high) / 2

        if net_charge(seq, mid) > 0:
            low = mid
        else:
            high = mid

    return round((low + high) / 2, 2)

def atomic_composition(protein):
    c = 0
    h = 0
    o = 0
    n = 0
    s = 0

    for aa in protein:
        if aa == 'A': #Alanine (Ala)
            c+=3
            h+=7
            o+=2
            n+=1
            s+=0
        if aa == 'R': #Arginine (Arg)
            c+=6
            h+=14
            o+=2
            n+=4
            s+=0
        if aa == 'N':#Asparagine (Asn)
            c+=4
            h+=8
            o+=3
            n+=2
            s+=0
        if aa == 'D':#Aspartic Acid (Asp)
            c+=4
            h+=7
            o+=4
            n+=1
            s+=0
        if aa == 'C':#Cysteine (Cys)
            c+=3
            h+=7
            o+=2
            n+=1
            s+=1
        if aa == 'Q':#Glutamine (Gln)
            c+=5
            h+=10
            o+=3
            n+=2
            s+=0
        if aa == 'E':#Glutamic Acid (Glu)
            c+=5
            h+=9
            o+=4
            n+=1
            s+=0
        if aa == 'G':#Glycine (Gly)
            c+=2
            h+=5
            o+=2
            n+=1
            s+=0
        if aa == 'H':#Histidine (His)
            c+=6
            h+=9
            o+=2
            n+=3
            s+=0
        if aa == 'I':#Isoleucine (Ile)
            c+=6
            h+=13
            o+=2
            n+=1
            s+=0
        if aa == 'L':#Leucine (Leu)
            c+=6
            h+=13
            o+=2
            n+=1
            s+=0
        if aa == 'K':#Lysine (Lys)
            c+=6
            h+=14
            o+=2
            n+=2
            s+=0
        if aa == 'M':#Methionine (Met)
            c+=5
            h+=11
            o+=2
            n+=1
            s+=1
        if aa == 'F':#Phenylalanine (Phe)
            c+=9
            h+=11
            o+=2
            n+=1
            s+=0
        if aa == 'P':#Proline (Pro)
            c+=5
            h+=9
            o+=2
            n+=1
            s+=0
        if aa == 'S':#Serine (Ser
            c+=3
            h+=7
            o+=3
            n+=1
            s+=0
        if aa == 'T':#Threonine (Thr)
            c+=4
            h+=9
            o+=3
            n+=1
            s+=0
        if aa == 'W':#Tryptophan (Trp)
            c+=11
            h+=12
            o+=2
            n+=2
            s+=0
        if aa == 'Y':#Tyrosine (Tyr)
            c+=9
            h+=11
            o+=3
            n+=1
            s+=0
        if aa == 'V':#Valine (Val)
            c+=5
            h+=11
            o+=2
            n+=1
            s+=0


            
    return c,h,o,n,s

def secondary_structure_fraction(protein):
    x = ProteinAnalysis(protein)
    raw_values = x.secondary_structure_fraction()
    rounded_values = tuple(round(value, 2) for value in raw_values)  # Round to 2 decimal places
    return rounded_values

def molar_extinction_coefficient(protein):
    x = ProteinAnalysis(protein)
    return(x.molar_extinction_coefficient())

def charge_at_pH(protein, ph):
    x = ProteinAnalysis(protein)
    return round(x.charge_at_pH(ph),2)

def count_amino_acids(protein):
    x = ProteinAnalysis(protein)
    return(x.count_amino_acids())

def get_amino_acids_percent(protein):
    x = ProteinAnalysis(protein)
    return x.get_amino_acids_percent()


def aa_counts(protein):
    allowed_aa = ['A','R','N','D','C','Q','E','G','H','I','K','L','M','F','P','S','T','W','Y','V']
    counts = {el: 0 for el in allowed_aa}

    for el in allowed_aa:
        counts[el] = protein.count(el)

    return counts
    


# Create your views here.
def test_view(request):
    return render(request, "protein_profiler/home.html")

def prot_char(request):
    if request.method == 'POST':
        form = proteinForm(request.POST, request.FILES)
        output = []
        stability = ""
        i=1

        if form.is_valid():
            collected_data = form.cleaned_data
            protein_text = collected_data.get('protein_text')
            uploaded_file = collected_data.get('uploaded_file')

            if uploaded_file:
                uploaded_file_data = uploaded_file.read().decode('utf-8')
                
                request.session['uploaded_file_data'] = uploaded_file_data
                
                uploaded_file_io = StringIO(uploaded_file_data)
                
                for record in SeqIO.parse(uploaded_file_io, "fasta"):

                    allowed_amino_acids = set("ARNDCQEGHIJKLMFPSTWYV")

                    if all(aa in allowed_amino_acids for aa in str(record.seq)):

                    
                        protein = record.seq
                        protein = str(protein)
                    
                        
                        description = record.description
                        accession = "NONE"

                        accession = description
                        accession = accession.split(" ")
                        accession = accession[0]
                        
                        if (instability_index(protein)) < 40:
                            stability = "Stable"
                        else:
                            stability = "Unstable"
                        

                        aa_percentage = get_amino_acids_percent(protein)
                        aa_percentage_non_zero = {k: round(v, 2) for k, v in aa_percentage.items() if v}
                        output.append({
                            'accession': accession,
                            'length': len(protein),
                            'gravy': gravy(protein),
                            'aliphatic_index': aliphatic_index(protein),
                            'instability_index': instability_index(protein),
                            'stability':stability,
                            'molecular_weight': molecular_weight(protein),
                            'aromaticity': aromaticity(protein),
                            'isoelectric_point': isoelectric_point(protein),
                            'amino_acid_count': count_amino_acids(protein),
                            'secondary_structure_fraction': secondary_structure_fraction(protein),
                            'molar_extinction_coefficient': molar_extinction_coefficient(protein),
                            'charge_at_pH': charge_at_pH(protein, 7),
                            'aa_counts': aa_counts(protein),
                            'description': description,
                            'sequence': protein,
                            'id':i,
                            'atomic_composition': atomic_composition(protein)
                        })
                        i+=1
                    

                                        

protein_profiler/templates/protein_profiler/about.html
{% extends 'base.html' %}

{% block content %}
<div class='content'>
<h1> How to use the app.</h1><br>
<h3> Do you have your own protein data that needs to be profiled?<br>
    Find below a step by step guide on how to use MPP.</h3>
    <br>
<ol>

<p><li>Video tutorial</li> </p> <br> 

<iframe width="650" height="360" src="https://www.youtube.com/embed/FpsvZINctog" title="Multiple Protein Profiler - How to use" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

<li><p> MPP is an integrated tool that allows the profiling of 12 individual properties of multiple proteins in a significant manner. <br>
    MPP provides a tabular and graphic visualization of properties of multiple proteins. </p></li><br>

<li><p>Upon acessing the home page of the MPP tool, you will find an option to input your proteins for MPP to profile.<br>
    You can either input proteins in a text format or upload a file. Either options work better with a .FASTA file format.</p></li><br>

    <div class="image-container ms-auto">
        <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/figure1.png" alt="Dal Logo" width="1200" height="500">
    </div>

<li><p>After clicking submit, your proteins will be profiled.</p></li><br>

<li><p>In the results, you have a table with the calculated properties of your proteins</p></li><br>
<li><p>You can click on <b>download profiled proteins as .csv</b></p></li><br>
<li><p>In the header, you can click on a particular property to be directed to the plot</p></li><br>

<div class="image-container ms-auto">
    <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/figure2.png" alt="Dal Logo" width="1200" height="500">
</div>
</ol>
</div>

{% endblock %}
    

protein_profiler/templates/protein_profiler/contact.html
{% extends 'base.html'%}

{%block content%}

<style>
.form-container {
    width: 100%;
    max-width: 600px;
    margin: 0 auto;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 10px;
    background-color: #f9f9f9;
}
.form-row {
    display: flex;
    align-items: center;
    margin-bottom: 15px;
}
.form-row label {
    width: 150px;
    margin-right: 10px;
    text-align: right;
    box-sizing: border-box;
}
.form-row input[type="text"],
.form-row input[type="email"],
.form-row textarea {
    flex: 1; 
    padding: 8px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
}
.form-row input[type="text"],
.form-row input[type="email"] {
    height: 38px; /* Ensure consistent height for text and email inputs */
}
.form-row textarea {
    height: 100px;
}
.form-buttons {
    display: flex;
    justify-content: flex-end;
    gap: 10px;
}
.form-buttons button {
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    background-color: #4ac4cf;
    color: black;
    cursor: pointer;
}

.form-buttons button[type="button"] {
    background-color: #6c757d;
}

</style>

<div class='content'>
    <h1>Reach out to us!</h1>

<div class="form-container">
    <form id="ContactForm" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row">
            <label for="{{ form.subject.id_for_label }}">Subject</label>
            {{ form.subject }}
        </div>
        <div class="form-row">
            <label for="{{ form.email.id_for_label }}">E-mail</label>
            {{ form.email }}
        </div>
        <div class="form-row">
            <label for="{{ form.message.id_for_label }}">Message</label>
            {{ form.message }}
        </div>
        <div class="form-row">
            <label for="{{ form.message.id_for_label }}"></label>
            {{ form.captcha }}
        </div>
        <div class="form-buttons">
            <button type="submit">Send</button>
           
        </div>
    </form>
</div>
</div>

<script>
    function clearForm() {
        document.getElementById("ContactForm").reset();
    }
</script>

{%endblock%}

protein_profiler/templates/protein_profiler/contact_success.html
{% extends 'base.html'%}

{%block content%}

<div class='content'>
<h2>Email successfully sent!</h2>
<p> Someone from our team will be in touch shortly. </p>

</div>
{% endblock%}

protein_profiler/templates/protein_profiler/download.html
{% extends 'base.html' %}

{% block content %}

<style>
    .download-button {
        background-color: #4ac4cf; 
        border: none; 
        color: black; 
        padding: 15px 32px; 
        text-align: center; 
        text-decoration: none; 
        display: inline-block; 
        font-size: 14px;
        margin: 4px 2px; 
        cursor: pointer; 
        border-radius: 8px; 
      }
    </style>

<div class='content'>
    <h1> Download the local executable.</h1><br>
<h3>Do you need to run MPP on a local machine?</h3>
    <br>

<iframe  width="650" height="360" src="https://www.youtube.com/embed/7J4pI9O2oT8" title="Multiple Protein Profiler - Local Executable" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

    <p>The dependencies for MPP to execute locally are</p>
    <ul>
    <li>A. Python 3.12</li>
    <li>B. The Bio Python package.</li>
    <li>C. A command line environment.</li>
    </ul>
    <br>
    <p>Once points A, B, and C are covered, proceed to:</p>
    
    <ol>
    <li>Download the mpp_local.zip file from link.</li>
        <li>Unzip the file.</li>
            <li>Create a working directory and move mpp.py to the working directory.</li>
                <li>Ensure you have Python3.12 installed and accessible through command line.</li>
                    <li>Install the Bio package.</li>
                            pip3.12 install Bio</li>
                            <li>After installation, you can execute mpp.py.</li>
                                <li>Select the input file containing the proteins you want to predict the physico-chemical structures in .fasta format.</li>
                                    <li>Specify the output file, preferably a .csv.</li>
    <br>
    <br>
    <p>The command of mpp.py should look like:
    
    <p>python3.12 mpp.py input_file.fasta output_file.csv</p>
    
    
    



    <a href="{% url 'protein_profiler:download_zip_file' %}" download class="download-button">
        Download Local Executable
    </a>

    </div>

<script>
    document.getElementById("downloadButton").addEventListener("click", function() {
        // Redirect to the URL of the download view
        window.location.href = "{% url 'protein_profiler:download_zip_file' %}";
    });
    </script>
{% endblock %}

protein_profiler/templates/protein_profiler/home.html
{% extends 'base.html' %}

{% block content %}

<a>Multiple Protein Profiler</a>


{% endblock %}

protein_profiler/templates/protein_profiler/plot.html
{% extends 'base.html' %}

{% block content %}
<head>
    <title>Length Distribution Plot</title>
</head>
<body>
    <img src="data:image/png;base64,{{ plot_image }}">
</body>


{% endblock %}

protein_profiler/templates/protein_profiler/prot_char.html
{% extends 'base.html' %}

{% block content %}
<style>
.submit-button {
    background-color: #4ac4cf; 
    border: none; 
    color: black; 
    padding: 15px 32px; 
    text-align: center; 
    text-decoration: none; 
    display: inline-block; 
    font-size: 16px;
    margin: 4px 2px; 
    cursor: pointer; 
    border-radius: 8px; 
  }
  
  .submit-button:hover {
    background-color: #3fabb5; 
  }
  .content-rectangle {
    border: 2px dashed #ccc; 
    background-color: rgba(255, 255, 255, 0.5); 
    padding: 10px; 
    border-radius: 10px; 
    width: fit-content; 
    margin: 10px 0; 
}

</style>
<div class='content'>
<h1>Multiple Protein Profiler (MPP)</h1>
<br>
<h2>MPP is an integrated tool that profiles 12<br>  individual properties of multiple proteins.</h2>
<br>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}
    <button type="submit" class="submit-button">Submit</button>

</form>
<br><br>
<div class='content-rectangle'>
<h3>If considering using MPP in your work, kindly cite us:</h3>
<p>Sganzerla Martinez, G., Dutt, M., Kumar, A., & Kelvin, D. J. (2024). <br>
    Multiple Protein Profiler 1.0 (MPP): <br>
    A Webserver for Predicting and Visualizing Physiochemical Properties of Proteins at the Proteome Level.<br>
    The Protein Journal.<br>
    <a href="https://doi.org/10.1007/s10930-024-10214-z" target="_blank">Read the article</a>
</div>
</div>
{% endblock %}

protein_profiler/templates/protein_profiler/publication.html
{% extends 'base.html' %}

{% block content %}

<div class='content'>

<h1>MPP has been published in a peer-reviewed journal.</h1>
<br>

<h2> If considering using MPP in your work, kindly cite us: </h2><br>


<p>Sganzerla Martinez, G., Dutt, M., Kumar, A., & Kelvin, D. J. (2024). <br>
Multiple Protein Profiler 1.0 (MPP): A Webserver for Predicting and Visualizing Physiochemical Properties of Proteins at the Proteome Level.<br>
The Protein Journal.<br>
<a href="https://doi.org/10.1007/s10930-024-10214-z" target="_blank">Read the article</a></p>


</div>
{% endblock %}

protein_profiler/templates/protein_profiler/submitted_prot_char.html
{% extends 'base.html' %}

{% block content %}

<head>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
            max-width: 800px;
            margin: 0;  /* Set left margin to 0 */
        }
    
        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }
    
        th {
            background-color: #f2f2f2;
        }
    
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    
        tr:hover {
            background-color: #e0e0e0;
        }
    
        th:first-child, td:first-child {
            text-align: center;
        }

        #scrollToTop {
            display: none; /* Hide the button by default */
            position: fixed;
            bottom: 20px;
            right: 20px;
            z-index: 99;
            background-color: #4ac4cf;
            color: black;
            border: none;
            border-radius: 50%;
            padding: 15px;
            text-align: center;
            font-size: 16px;
            cursor: pointer;
        }
        .button-container {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
        }
        
        .button-container a {
            display: inline-block;
            width: 250px; /* Set a fixed width for the buttons */
            padding: 10px; /* Adjust padding as needed */
            margin-bottom: 5px; /* Adjust spacing between buttons if needed */
            text-align: center; /* Center the text inside the buttons */
            text-decoration: none; /* Remove underline from links */
            background-color: #4ac4cf; /* Background color for the buttons */
            color: black; /* Text color */
            border: none; /* Remove borders */
            border-radius: 5px; /* Optional: Rounded corners */
            cursor: pointer; /* Pointer/hand icon */
        }
        .download-button {
            background-color: #4ac4cf; 
            border: none; 
            color: black; 
            padding: 15px 32px; 
            text-align: center; 
            text-decoration: none; 
            display: inline-block; 
            font-size: 14px;
            margin: 4px 2px; 
            cursor: pointer; 
            border-radius: 8px; 
          }

    </style>
    </head>

  
    <body>
        <h1>Results</h1>
        {% if csv_content %}
        <div class="button-container">
            <a href="{% url 'protein_profiler:download_csv' %}" download class="download-button">
                Download Profiled Proteins as .csv
            </a>
            <br>
            <a href="{% url 'protein_profiler:download_plots' %}" download class="download-button">
                Download Zipped Plots
            </a>
        </div>
        

    <br>
{% endif %}
    <table>
        <thead>
            <tr>
                <th>Acession</th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='length' %}" target="_blank">Length</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='gravy' %}" target="_blank">GRAVY</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='aliphatic_index' %}" target="_blank">Aliphatic Index</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='instability_index' %}" target="_blank">Instability Index</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='stability' %}" target="_blank">Stability</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='molecular_weight' %}" target="_blank">Molecular Weight</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='aromaticity' %}" target="_blank">Aromaticity</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='isoelectric_point' %}" target="_blank">Isoelectric Point</a>
                </th>
                <th>
                    <a href="{% url 'protein_profiler:plot' choice='charge_at_pH' %}" target="_blank">Charge at pH 7</a>
                </th>
                <th>Secondary Structure Fraction (Helix; Turn; Sheet)</th>
                <th>Molar Extinction Coefficient (Reduced; Oxidized)</th>
                <th>Atomic Composition</th>
                <th>A counts</th>
                <th>R counts</th>
                <th>N counts</th>
                <th>D counts</th>
                <th>C counts</th>
                <th>Q counts</th>
                <th>E counts</th>
                <th>G counts</th>
                <th>H counts</th>
                <th>I counts</th>
                <th>K counts</th>
                <th>L counts</th>
                <th>M counts</th>
                <th>F counts</th>
                <th>P counts</th>
                <th>S counts</th>
                <th>T counts</th>
                <th>W counts</th>
                <th>Y counts</th>
                <th>V counts</th>
               
            </tr>
        </thead>
        <tbody>
            {% for item in output %}
            <tr>
                <td> <a href="{% url 'protein_profiler:view_protein' id=item.id%}">{{ item.accession }}</td></a>
                <td>{{item.length}}</td>
                <td>{{item.gravy}}</td>
                <td>{{item.aliphatic_index}}</td>
                <td>{{item.instability_index}}</td>
                <td>{{item.stability}}</td>
                <td>{{item.molecular_weight}}</td>
                <td>{{item.aromaticity}}</td>
                <td>{{item.isoelectric_point}}</td>
                <td>{{item.charge_at_pH}}</td>
                <td>
                    <ul>
                        {% for value in item.secondary_structure_fraction %}
                        <li>{{value}}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <ul>
                        {% for value in item.molar_extinction_coefficient %}
                        <li>{{value}}</li>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    C<sub>{{ item.atomic_composition.0 }}</sub>
                    H<sub>{{ item.atomic_composition.1 }}</sub>
                    O<sub>{{ item.atomic_composition.2 }}</sub>
                    N<sub>{{ item.atomic_composition.3 }}</sub>
                    S<sub>{{ item.atomic_composition.4 }}</sub>
                </td>
                {% for count in item.aa_counts.values %}
                <td>{{count}}
                    {% endfor %}
            {% endfor %}
        </tbody>
    </table>

    <!-- Button to scroll to the top -->
    <button id="scrollToTop" onclick="scrollToTop()">Back to Top</button>

    <script>
        // Show the button when the user scrolls down 20px from the top of the document
        window.onscroll = function() {
            scrollFunction();
        };

        function scrollFunction() {
            var button = document.getElementById("scrollToTop");
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                button.style.display = "block";
            } else {
                button.style.display = "none";
            }
        }

        // Scroll to the top of the document when the button is clicked
        function scrollToTop() {
            document.body.scrollTop = 0; // For Safari
            document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE, and Opera
        }
    </script>


    </body>
    </html>
    
    {% endblock %}
    

    