DjangoApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('protein_profiler/', include('protein_profiler.urls'))
]

protein_profiler/urls.py
from django.urls import path
from . import views


app_name = "protein_profiler"

urlpatterns = [
    path('test_view/', views.test_view, name = "test_view"),
    path('prot_char/', views.prot_char, name = "prot_char"),
    path('submitted_prot_char/', views.submitted_prot_char, name = "submitted_prot_char"),
    path('download_csv/', views.download_csv, name = "download_csv"),
    path('view_protein/<str:id>/', views.view_protein, name='view_protein'),
    path('plot/<str:choice>/', views.plot, name='plot'),
    path('how_to_use/', views.how_to_use, name = 'how_to_use'),
    path('download/', views.download, name = 'download'),
    path('download_zip_file/', views.download_zip_file, name = 'download_zip_file'),
    path('publication/', views.publication, name = 'publication'),
    path('download_plots/', views.download_plots, name = 'download_plots'),
    path('contact/', views.contact, name = 'contact')
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">



<style>
    .content {
        margin-left: 20px; /* Adjust based on navbar width */
        padding: 20px;
    }
</style>


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MPP</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/d4ed401b86.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="master_bts_forms.css">


    <nav class="navbar avbar-light navbar-expand-lg" style="background-color: #F0F8FF;">
      <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <div class="navbar-nav">
                  <a class="navbar-brand" href="{%url 'protein_profiler:prot_char'%}" ><b>Home</b></a>
                  <a class="nav-link" href="{%url 'protein_profiler:how_to_use'%}">How to use</a> 
                  <a class="nav-link" href="{%url 'protein_profiler:download'%}">Download</a>
                  <a class="nav-link" href="{%url 'protein_profiler:publication'%}">Publication</a>
                  <a class="nav-link" href="{%url 'protein_profiler:contact'%}">Contact</a>
              </div>
              
          </div>
          <div class="image-container ms-auto">
            <div class="image-container ms-auto">
                <a href = "https://www.dal.ca/" target = "_blank">
                <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/dal.png" alt="Dal Logo" width="75" height="75">
                </a>
            </div>
            
        </div>
      </div>
    </nav>
</head>
<body style="display: flex; flex-direction: column; min-height: 100vh;">
    

  <div class="flex-grow-1">
    {% block content %}
    
    {% endblock %}
  </div>
  </body>

  <footer class="bg-secondary text-black text-center" style="background-color: #F0F8FF !important;">
    <a href = "https://www.dal.ca/" target = "_blank">
    <img src="https://raw.githubusercontent.com/gustavsganzerla/mpp/main/protein_profiler/static/images/dal_fm.png" alt="Dal Logo" width="250" height="100">
    </a>
    <p style="margin-bottom: 3px;">Department of Microbiology & Immunology</p>
    <p style="margin-bottom: 3px;">&copy; 2023-2024 Laboratory of Emerging Infectious Diseases</p>
    <p style="margin-bottom: 3px;"><a href="{%url 'protein_profiler:publication'%}">Publication</a></p>
    <p style="margin-bottom: 3px;">
        <a href="https://github.com/gustavsganzerla/mpp">
            <i class="fab fa-github"></i> GitHub
        </a>
    </p>
</footer>



</html>